webtalk_init -webtalk_dir C:/Users/ryban/OneDrive/Desktop/RISC-V-Processor/rv32i_pipelined/rv32i_pipelined.sim/sim_4/behav/xsim/xsim.dir/RV32I_pipelined_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 11 00:08:16 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ea2e1ffd-1610-4d8e-8431-9c7b9d6791a6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bd6bf5eee7d641d489ebaa473494efaf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "29" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "75" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "927 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "68 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "658" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "84" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "5.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "207876_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2995059751 -regid "" -xml C:/Users/ryban/OneDrive/Desktop/RISC-V-Processor/rv32i_pipelined/rv32i_pipelined.sim/sim_4/behav/xsim/xsim.dir/RV32I_pipelined_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ryban/OneDrive/Desktop/RISC-V-Processor/rv32i_pipelined/rv32i_pipelined.sim/sim_4/behav/xsim/xsim.dir/RV32I_pipelined_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ryban/OneDrive/Desktop/RISC-V-Processor/rv32i_pipelined/rv32i_pipelined.sim/sim_4/behav/xsim/xsim.dir/RV32I_pipelined_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
