@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Apr 11 00:08:16 -0400 2019
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim RV32I_pipelined_tb_behav -key {Behavioral:sim_4:Functional:RV32I_pipelined_tb} -tclbatch RV32I_pipelined_tb.tcl -protoinst "protoinst_files/RV32I_pipelined.protoinst" -view C:/Users/ryban/OneDrive/Desktop/RISC-V-Processor/rv32i_pipelined/rv32i_pipelined.srcs/sim_4/imports/rv32i_pipelined/RV32I_pipelined_tb_behav3.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
