# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Alex/Documents/RISC-V-Processor/terminal/terminal.srcs/sources_1/ip/picture/picture.xci
# IP: The module: 'picture' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alex/Documents/RISC-V-Processor/terminal/terminal.srcs/sources_1/ip/picture/picture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Alex/Documents/RISC-V-Processor/terminal/terminal.srcs/sources_1/ip/picture/picture.xci
# IP: The module: 'picture' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alex/Documents/RISC-V-Processor/terminal/terminal.srcs/sources_1/ip/picture/picture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
