# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/.Xil/Vivado-3508-Nugget/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.cache/wt [current_project]
set_property parent.project_path C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.srcs/sources_1/imports/Desktop/Capstone/fontROM.vhd
  C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.srcs/sources_1/new/terminal_top.vhd
  {C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.srcs/sources_1/imports/Desktop/Embedded/Lab 4/lab-4-submission-JonColella/Lab 4.srcs/sources_1/new/vga_ctrl.vhd}
  C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.srcs/sources_1/new/character_memaddress.vhd
  C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.srcs/sources_1/new/Font_Rom_Addr_Gen.vhd
  C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.srcs/sources_1/new/Pixel_Pusher.vhd
  C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.srcs/sources_1/new/clock_div.vhd
  C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.srcs/sources_1/new/pixel_selector.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.srcs/constrs_1/imports/2/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Jon/Desktop/capstone/RISC-V-Processor/terminal/terminal.srcs/constrs_1/imports/2/ZYBO_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top terminal_top -part xc7z010clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef terminal_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file terminal_top_utilization_synth.rpt -pb terminal_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
