# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/ZYBO_MASTER.xdc

# Block Designs: bd/RV32I_pipelined/RV32I_pipelined.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined || ORIG_REF_NAME==RV32I_pipelined} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_ALU_0_0/RV32I_pipelined_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_ALU_0_0 || ORIG_REF_NAME==RV32I_pipelined_ALU_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_Descrambler_0_0/RV32I_pipelined_Descrambler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_Descrambler_0_0 || ORIG_REF_NAME==RV32I_pipelined_Descrambler_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_RV32I_0_0/RV32I_pipelined_RV32I_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_RV32I_0_0 || ORIG_REF_NAME==RV32I_pipelined_RV32I_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_alu_signals_0_0/RV32I_pipelined_alu_signals_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_alu_signals_0_0 || ORIG_REF_NAME==RV32I_pipelined_alu_signals_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_blk_mem_gen_0_0/RV32I_pipelined_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_blk_mem_gen_0_0 || ORIG_REF_NAME==RV32I_pipelined_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_brach_logic_0_0/RV32I_pipelined_brach_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_brach_logic_0_0 || ORIG_REF_NAME==RV32I_pipelined_brach_logic_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_clk_wiz_0_0/RV32I_pipelined_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_clk_wiz_0_0 || ORIG_REF_NAME==RV32I_pipelined_clk_wiz_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_clock_div_0_0/RV32I_pipelined_clock_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_clock_div_0_0 || ORIG_REF_NAME==RV32I_pipelined_clock_div_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_debounce_0_0/RV32I_pipelined_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_debounce_0_0 || ORIG_REF_NAME==RV32I_pipelined_debounce_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_hazard_count_0_0/RV32I_pipelined_hazard_count_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_hazard_count_0_0 || ORIG_REF_NAME==RV32I_pipelined_hazard_count_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_hazard_logic_0_0/RV32I_pipelined_hazard_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_hazard_logic_0_0 || ORIG_REF_NAME==RV32I_pipelined_hazard_logic_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_instruction_clear_0_0/RV32I_pipelined_instruction_clear_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_instruction_clear_0_0 || ORIG_REF_NAME==RV32I_pipelined_instruction_clear_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_mux_output_0_0/RV32I_pipelined_mux_output_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_mux_output_0_0 || ORIG_REF_NAME==RV32I_pipelined_mux_output_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_mux_reg_descr_alu_0_0/RV32I_pipelined_mux_reg_descr_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_mux_reg_descr_alu_0_0 || ORIG_REF_NAME==RV32I_pipelined_mux_reg_descr_alu_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_mux_reg_pc_alu_0_0/RV32I_pipelined_mux_reg_pc_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_mux_reg_pc_alu_0_0 || ORIG_REF_NAME==RV32I_pipelined_mux_reg_pc_alu_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_mux_reg_write_0_0/RV32I_pipelined_mux_reg_write_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_mux_reg_write_0_0 || ORIG_REF_NAME==RV32I_pipelined_mux_reg_write_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_pc_logic_0_0/RV32I_pipelined_pc_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_pc_logic_0_0 || ORIG_REF_NAME==RV32I_pipelined_pc_logic_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_pc_shift_down_0_0/RV32I_pipelined_pc_shift_down_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_pc_shift_down_0_0 || ORIG_REF_NAME==RV32I_pipelined_pc_shift_down_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_post_memory_logic_0_0/RV32I_pipelined_post_memory_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_post_memory_logic_0_0 || ORIG_REF_NAME==RV32I_pipelined_post_memory_logic_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_pre_memory_logic_0_0/RV32I_pipelined_pre_memory_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_pre_memory_logic_0_0 || ORIG_REF_NAME==RV32I_pipelined_pre_memory_logic_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_program_counter_1_0/RV32I_pipelined_program_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_program_counter_1_0 || ORIG_REF_NAME==RV32I_pipelined_program_counter_1_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_registers_0_0/RV32I_pipelined_registers_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_registers_0_0 || ORIG_REF_NAME==RV32I_pipelined_registers_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_stage_DE_0_0/RV32I_pipelined_stage_DE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_stage_DE_0_0 || ORIG_REF_NAME==RV32I_pipelined_stage_DE_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_stage_EM_0_0/RV32I_pipelined_stage_EM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_stage_EM_0_0 || ORIG_REF_NAME==RV32I_pipelined_stage_EM_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_stage_FD_0_0/RV32I_pipelined_stage_FD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_stage_FD_0_0 || ORIG_REF_NAME==RV32I_pipelined_stage_FD_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_stage_MW_0_0/RV32I_pipelined_stage_MW_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_stage_MW_0_0 || ORIG_REF_NAME==RV32I_pipelined_stage_MW_0_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_blk_mem_gen_1_0/RV32I_pipelined_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_blk_mem_gen_1_0 || ORIG_REF_NAME==RV32I_pipelined_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_clock_div_1_0/RV32I_pipelined_clock_div_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_clock_div_1_0 || ORIG_REF_NAME==RV32I_pipelined_clock_div_1_0} -quiet] -quiet

# IP: bd/RV32I_pipelined/ip/RV32I_pipelined_terminal_tld_0_0/RV32I_pipelined_terminal_tld_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV32I_pipelined_terminal_tld_0_0 || ORIG_REF_NAME==RV32I_pipelined_terminal_tld_0_0} -quiet] -quiet

# XDC: bd/RV32I_pipelined/RV32I_pipelined_ooc.xdc
